# Predicting the yeild of apples and oranges based on temperature, rainfall and humidity
![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In [102]:
import numpy as np
import torch

In [103]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [104]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [105]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [106]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.4363,  1.0593,  2.1191],
        [ 0.4323,  0.7754, -0.3234]], requires_grad=True)
tensor([-2.2620,  0.4004], requires_grad=True)


In [107]:
def model(x):
  return x @ w.t() + b

In [108]:
preds = model(inputs)
print(preds)

tensor([[127.9864,  69.9992],
        [186.8802,  87.2713],
        [224.6405, 123.1502],
        [ 77.1962,  65.8660],
        [217.6671,  82.0243]], grad_fn=<AddBackward0>)


In [109]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [110]:
def mse(t1, t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()


In [111]:
loss = mse(preds, targets)
print(loss)

tensor(4623.3682, grad_fn=<DivBackward0>)


In [112]:
loss.backward()

In [113]:
print(w)
print(w.grad)

tensor([[-0.4363,  1.0593,  2.1191],
        [ 0.4323,  0.7754, -0.3234]], requires_grad=True)
tensor([[7524.5737, 8335.5703, 5213.5703],
        [-342.6592, -967.2966, -594.0436]])


In [114]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [115]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(3214.7239, grad_fn=<DivBackward0>)


In [116]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [117]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[114.6659,  71.1529],
        [169.3599,  88.8146],
        [203.8996, 125.0891],
        [ 64.0069,  66.8513],
        [200.8226,  83.6052]], grad_fn=<AddBackward0>)


In [118]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(3214.7239, grad_fn=<DivBackward0>)


In [119]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[6148.8184, 6856.0210, 4300.7363],
        [-222.0732, -833.8851, -512.4521]])
tensor([74.3510, -4.8974])


In [120]:
# Adjust the wts and reset the gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()


In [121]:
print(w)
print(b)

tensor([[-0.5730,  0.9074,  2.0239],
        [ 0.4379,  0.7934, -0.3123]], requires_grad=True)
tensor([-2.2637,  0.4005], requires_grad=True)


In [122]:
# With new wts and bias the loss
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(2264.7183, grad_fn=<DivBackward0>)


Train for multiple epochs

In [123]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
      w -= w.grad * 1e-5
      b -= b.grad * 1e-5
      w.grad.zero_()
      b.grad.zero_()


In [124]:
# Once again verify the loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(165.7945, grad_fn=<DivBackward0>)


In [125]:
# Compare with the model's prediction with the actual value
preds

tensor([[ 54.6960,  74.0468],
        [ 89.1131,  94.8491],
        [106.9486, 140.1897],
        [  9.7988,  57.5100],
        [120.0720,  97.1299]], grad_fn=<AddBackward0>)

In [126]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [127]:
# The predictions are much closer to the actual values
# This was done with the basic operations of tensors and now lets try with the inbuilt functions

#
#Implementing the model with the Pytorch's inbuilt functions

In [128]:
import torch.nn as nn

In [129]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [130]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [131]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [132]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [133]:
from torch.utils.data import TensorDataset

In [134]:
# Define datasets
# The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [135]:
from torch.utils.data import DataLoader

In [136]:
# DataLoader splits the data into batches of a predefined size while training . It provides shuffling and random shuffling as well

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [137]:
# For loading in multiple batches
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[102.,  43.,  37.],
        [ 73.,  66.,  44.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 91.,  87.,  65.]])
tensor([[ 22.,  37.],
        [ 57.,  69.],
        [ 21.,  38.],
        [104., 118.],
        [ 80., 102.]])


In [138]:
# Define the model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3539,  0.0343, -0.0590],
        [-0.2373,  0.2988, -0.5313]], requires_grad=True)
Parameter containing:
tensor([ 0.1906, -0.0402], requires_grad=True)


In [139]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3539,  0.0343, -0.0590],
         [-0.2373,  0.2988, -0.5313]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1906, -0.0402], requires_grad=True)]

In [140]:
preds = model(inputs)
print(preds)

tensor([[ 25.7877, -20.1892],
        [ 31.6392, -29.3435],
        [ 32.1556, -11.4617],
        [ 35.5828, -31.0529],
        [ 23.7729, -24.9213],
        [ 26.1074, -20.7252],
        [ 31.5459, -30.1736],
        [ 32.4505, -12.2303],
        [ 35.2632, -30.5169],
        [ 23.3599, -25.2154],
        [ 25.6944, -21.0193],
        [ 31.9589, -29.8795],
        [ 32.2489, -10.6316],
        [ 35.9958, -30.7589],
        [ 23.4533, -24.3852]], grad_fn=<AddmmBackward>)


In [141]:
import torch.nn.functional as F

In [142]:
loss_fn = F.mse_loss

In [143]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8875.7754, grad_fn=<MseLossBackward>)


In [144]:
# Optimization
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [145]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [151]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], Loss: 28.1430
Epoch [20/1000], Loss: 52.2499
Epoch [30/1000], Loss: 39.2448
Epoch [40/1000], Loss: 31.4048
Epoch [50/1000], Loss: 49.3599
Epoch [60/1000], Loss: 32.0856
Epoch [70/1000], Loss: 34.2993
Epoch [80/1000], Loss: 31.4401
Epoch [90/1000], Loss: 20.4156
Epoch [100/1000], Loss: 26.2051
Epoch [110/1000], Loss: 34.8386
Epoch [120/1000], Loss: 12.5419
Epoch [130/1000], Loss: 26.0029
Epoch [140/1000], Loss: 21.0050
Epoch [150/1000], Loss: 15.2140
Epoch [160/1000], Loss: 20.2617
Epoch [170/1000], Loss: 10.8688
Epoch [180/1000], Loss: 15.9003
Epoch [190/1000], Loss: 4.9559
Epoch [200/1000], Loss: 20.4173
Epoch [210/1000], Loss: 10.2079
Epoch [220/1000], Loss: 22.3665
Epoch [230/1000], Loss: 16.3410
Epoch [240/1000], Loss: 12.4336
Epoch [250/1000], Loss: 9.1412
Epoch [260/1000], Loss: 10.1669
Epoch [270/1000], Loss: 10.3128
Epoch [280/1000], Loss: 4.1974
Epoch [290/1000], Loss: 10.7978
Epoch [300/1000], Loss: 9.3061
Epoch [310/1000], Loss: 7.0001
Epoch [320/1000], Loss

In [152]:
# genrate predictions 
preds = model(inputs)
print(preds)

tensor([[ 57.0150,  70.4228],
        [ 81.9003, 100.2622],
        [118.4993, 133.3882],
        [ 20.9033,  37.9098],
        [101.6104, 117.9224],
        [ 55.7640,  69.3386],
        [ 81.7308, 100.3064],
        [118.7776, 133.9625],
        [ 22.1543,  38.9940],
        [102.6919, 119.0508],
        [ 56.8455,  70.4670],
        [ 80.6493,  99.1780],
        [118.6688, 133.3439],
        [ 19.8218,  36.7814],
        [102.8615, 119.0065]], grad_fn=<AddmmBackward>)


In [153]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [154]:
error =mse(preds, targets)

In [155]:
print(error)

tensor(1.1328, grad_fn=<DivBackward0>)
